# -*- coding: utf-8 -*-
"""calculadora.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EnEhspNbfJ2q1yGEOqrnwjh_NhVskvKm

#Função calculadora
Faça uma função calculadora de dois números com três parâmetros: os dois primeiros serão os números da operação e o terceiro será a entrada que definirá a operação a ser executada. Considera a seguinte definição:
1. Soma
2. Subtração
3. Multiplicação
4. Divisão

Caso seja inserido um número de operação que não exista, o resultado deverá ser 0.
"""

def calculadora(primeiro_num, segundo_num, operacao):
  if( operacao == 1):
    if( segundo_num >= 0):
      print(primeiro_num, "+", segundo_num, " = ", primeiro_num + segundo_num)
    else:
      print(primeiro_num, "-", segundo_num/-1, " = ", primeiro_num + segundo_num)
  elif(operacao == 2):
    if( segundo_num >= 0):
      print(primeiro_num, "-", segundo_num, " = ", primeiro_num - segundo_num)
    else:
      print(primeiro_num, segundo_num, " = ", primeiro_num + segundo_num)
  elif(operacao == 3):
    print("(", primeiro_num,")", "*", "(", segundo_num, ")", " = ", primeiro_num * segundo_num)
  elif(operacao == 4):
    if(segundo_num != 0):
      print("(", primeiro_num, ")", "/", "(", segundo_num, ")", " = ", primeiro_num / segundo_num)
    else:
      print("Para divisão, o segundo número precisar ser diferente de 0.")
  else:
    print(0)

print("Soma")
calculadora(10, 3 , 1)
calculadora(10, -4, 1)
calculadora(-12, -4, 1)
print()

print("Subtração")
calculadora(7, 2, 2)
calculadora(22, -8, 2)
calculadora(-35, -12, 2)
print()

print("Multiplicação")
calculadora(10, 10, 3)
calculadora(10, -54, 3)
print()

print("Divisão")
calculadora(10, 10, 4)
calculadora(10, -5, 4)
calculadora(-10, -5, 4)
calculadora(3, 0, 4)
print()

print("Opção inexistente")
calculadora(10, 10, 5)
calculadora(10, -5, 11)
calculadora(-10, -5, 7)
calculadora(3, 0, 13)